#!/usr/bin/env bash
#
# scripts/create-pr.sh
#
# Idempotently commit FVT test changes in the workspace and open a GitHub pull
# request. All credentials are read from environment variables; nothing is
# committed to the example repository itself.
#
# Required environment variables:
#   GITHUB_TOKEN   - GitHub token with repo and workflow scopes
#   GITHUB_REPO    - Target repository slug, e.g. "owner/repo"
#
# Optional environment variables:
#   GIT_USER_NAME  - Git commit author name (default: Agentic Harness)
#   GIT_USER_EMAIL - Git commit author email (default: agentic-harness@example.local)
#
# Usage:
#   ./scripts/create-pr.sh <workspace-path>

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "[create-pr] ERROR: workspace path argument is required." >&2
  echo "[create-pr] Usage: $0 <workspace-path>" >&2
  exit 1
fi

WORKSPACE_PATH="$1"

# Validate required credentials
if [ -z "${GITHUB_TOKEN:-}" ]; then
  echo "[create-pr] ERROR: GITHUB_TOKEN environment variable is required." >&2
  exit 1
fi

if [ -z "${GITHUB_REPO:-}" ]; then
  echo "[create-pr] ERROR: GITHUB_REPO environment variable is required." >&2
  exit 1
fi

if [ ! -d "${WORKSPACE_PATH}" ]; then
  echo "[create-pr] ERROR: workspace path does not exist: ${WORKSPACE_PATH}" >&2
  exit 1
fi

GIT_USER_NAME="${GIT_USER_NAME:-Agentic Harness}"
GIT_USER_EMAIL="${GIT_USER_EMAIL:-agentic-harness@example.local}"

# Look for the samples repository inside the workspace
SAMPLES_DIR="${WORKSPACE_PATH}/inputs/code-engine-samples"
if [ ! -d "${SAMPLES_DIR}" ]; then
  echo "[create-pr] No samples repo found at ${SAMPLES_DIR}; nothing to commit."
  exit 0
fi

# Idempotent: only proceed when there are changes to commit
if [ -z "$(git -C "${SAMPLES_DIR}" status --porcelain 2>/dev/null || true)" ]; then
  echo "[create-pr] No FVT changes to commit in ${SAMPLES_DIR}."
  exit 0
fi

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BRANCH_NAME="agentic-loop-fvt-${TIMESTAMP}"

# Configure git user for this repo
git -C "${SAMPLES_DIR}" config user.name "${GIT_USER_NAME}"
git -C "${SAMPLES_DIR}" config user.email "${GIT_USER_EMAIL}"

# Create branch and commit FVT changes
git -C "${SAMPLES_DIR}" checkout -b "${BRANCH_NAME}"
git -C "${SAMPLES_DIR}" add -A
git -C "${SAMPLES_DIR}" commit -m "feat(fvt): agentic harness FVT coverage improvements [${TIMESTAMP}]"

# Push to origin using the token over HTTPS
REMOTE_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git"
git -C "${SAMPLES_DIR}" push "${REMOTE_URL}" "${BRANCH_NAME}"

# Open the pull request
PR_TITLE="feat: agentic-loop FVT coverage improvements"
PR_BODY="Automated FVT coverage improvements generated by the Agentic Harness.

- Discovers samples in inputs/code-engine-samples/samples/ai/
- Infers test frameworks from package.json/requirements.txt
- Adds or extends FVT tests to increase line coverage
- Stops when coverage reaches 100% or improvement stalls at <= 5%
"

if command -v gh > /dev/null 2>&1; then
  # Use GitHub CLI if available
  GH_TOKEN="${GITHUB_TOKEN}" gh pr create \
    --repo "${GITHUB_REPO}" \
    --title "${PR_TITLE}" \
    --body "${PR_BODY}" \
    --head "${BRANCH_NAME}" \
    --base "master"
else
  # Fallback to curl against the GitHub REST API
  curl -sS -X POST \
    -H "Authorization: token ${GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    "https://api.github.com/repos/${GITHUB_REPO}/pulls" \
    -d "$(printf '{"title":"%s","body":"%s","head":"%s","base":"master"}' \
      "${PR_TITLE}" \
      "${PR_BODY//$'\n'/\\n}" \
      "${BRANCH_NAME}")"
fi

echo "[create-pr] Pull request created from branch ${BRANCH_NAME}."
